--This is used in the @examples in query.R > sqlFileExecute
SELECT TOP 6 CUST_NAME,
REGEXP_REPLACE('$' || ROUND(SUM(SLS_AMT) / 1000000, 2) || 'M',' ', '') Sales
FROM SALES,
CUSTOMER
WHERE SALES.CUST_KEY = CUSTOMER.CUST_KEY
AND SALES.CUST_CD = CUSTOMER.CUST_CD
AND CUST_NAME IS NOT NULL
GROUP BY CUST_NAME
ORDER BY Sales DESC
